// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: example_project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
void ui_event_time_button(lv_event_t *e);
lv_obj_t *ui_time_button;
lv_obj_t *ui_time;
void ui_event_date_button(lv_event_t *e);
lv_obj_t *ui_date_button;
lv_obj_t *ui_date;
void ui_event_logo_button(lv_event_t *e);
lv_obj_t *ui_logo_button;
lv_obj_t *ui_logo;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_time_button(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        timePressed(e);
    }
}
void ui_event_date_button(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        datePressed(e);
    }
}
void ui_event_logo_button(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        logoPressed(e);
    }
}

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_button = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_time_button, 179);
    lv_obj_set_height(ui_time_button, 48);
    lv_obj_set_x(ui_time_button, 0);
    lv_obj_set_y(ui_time_button, -56);
    lv_obj_set_align(ui_time_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_time_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_time_button, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_time_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_time_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_time_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_time_button);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_time, -4);
    lv_obj_set_y(ui_time, 4);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "12:25:45");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_clock_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date_button = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_date_button, 166);
    lv_obj_set_height(ui_date_button, 17);
    lv_obj_set_x(ui_date_button, 0);
    lv_obj_set_y(ui_date_button, -18);
    lv_obj_set_align(ui_date_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_date_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_date_button, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_date_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_date_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_date_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_date_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_date_button);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "Mon 26 Dec 2023");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo_button = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_logo_button, 86);
    lv_obj_set_height(ui_logo_button, 85);
    lv_obj_set_x(ui_logo_button, 0);
    lv_obj_set_y(ui_logo_button, 37);
    lv_obj_set_align(ui_logo_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_logo_button, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_logo_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_logo_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_logo_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_logo_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_img_create(ui_logo_button);
    lv_img_set_src(ui_logo, &ui_img_sls_logo_png);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_logo, 180);

    lv_obj_add_event_cb(ui_time_button, ui_event_time_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_date_button, ui_event_date_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_logo_button, ui_event_logo_button, LV_EVENT_ALL, NULL);
}

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
