#include <Arduino.h>
#include "ui/lv_setup.h"
#include "ui/ui.h"

void setup()
{
  lv_begin(); // Initialize lvgl with display and rotary encoder
  ui_init();  // Initialize UI generated by Square Line
}

void loop()
{
  lv_handler(); // Update UI
}